---
# Default values for prefix-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# NOTE: the variables might be overriden by helm command line options, see helm.mk
registry: docker.io
org: aveshasystems
tag: 0.6.1
pullPolicy: IfNotPresent

serviceAccount:
  name: nsmgr-acc
